version: '3.5'
services:
  paniwala_api:
    image: paniwala_rest_api
    container_name: paniwala_api
    build:
      context: ./
    ports:
      - 8001:80
    volumes: 
      - ./src:/var/www/html/
      - ./vscode-server:/root/.vscode-server
    # depends_on:
    #   - data_base
    # networks:
    #   - web
networks: 
  default: 
    external: 
      name: vishva 